//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BimManager.Sunat.WS_Sunat_Consulta_Validez {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.sunat.gob.pe", ConfigurationName="WS_Sunat_Consulta_Validez.billValidService")]
    public interface billValidService {
        
        // CODEGEN: Parameter 'archivoverificado' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:verificaCPEarchivo", ReplyAction="http://service.sunat.gob.pe/billValidService/verificaCPEarchivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="archivoverificado")]
        BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoResponse verificaCPEarchivo(BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:verificaCPEarchivo", ReplyAction="http://service.sunat.gob.pe/billValidService/verificaCPEarchivoResponse")]
        System.Threading.Tasks.Task<BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoResponse> verificaCPEarchivoAsync(BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest request);
        
        // CODEGEN: Parameter 'cdpvalidado' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:validaCDPcriterios", ReplyAction="http://service.sunat.gob.pe/billValidService/validaCDPcriteriosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cdpvalidado")]
        BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosResponse validaCDPcriterios(BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:validaCDPcriterios", ReplyAction="http://service.sunat.gob.pe/billValidService/validaCDPcriteriosResponse")]
        System.Threading.Tasks.Task<BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosResponse> validaCDPcriteriosAsync(BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sunat.gob.pe")]
    public partial class statusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] contentField;
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificaCPEarchivo", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class verificaCPEarchivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string archivo;
        
        public verificaCPEarchivoRequest() {
        }
        
        public verificaCPEarchivoRequest(string nombre, string archivo) {
            this.nombre = nombre;
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificaCPEarchivoResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class verificaCPEarchivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BimManager.Sunat.WS_Sunat_Consulta_Validez.statusResponse archivoverificado;
        
        public verificaCPEarchivoResponse() {
        }
        
        public verificaCPEarchivoResponse(BimManager.Sunat.WS_Sunat_Consulta_Validez.statusResponse archivoverificado) {
            this.archivoverificado = archivoverificado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaCDPcriterios", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class validaCDPcriteriosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoCDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serieCDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroCDP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocIdReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocIdReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaEmision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double importeTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nroAutorizacion;
        
        public validaCDPcriteriosRequest() {
        }
        
        public validaCDPcriteriosRequest(string rucEmisor, string tipoCDP, string serieCDP, string numeroCDP, string tipoDocIdReceptor, string numeroDocIdReceptor, string fechaEmision, double importeTotal, string nroAutorizacion) {
            this.rucEmisor = rucEmisor;
            this.tipoCDP = tipoCDP;
            this.serieCDP = serieCDP;
            this.numeroCDP = numeroCDP;
            this.tipoDocIdReceptor = tipoDocIdReceptor;
            this.numeroDocIdReceptor = numeroDocIdReceptor;
            this.fechaEmision = fechaEmision;
            this.importeTotal = importeTotal;
            this.nroAutorizacion = nroAutorizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaCDPcriteriosResponse", WrapperNamespace="http://service.sunat.gob.pe", IsWrapped=true)]
    public partial class validaCDPcriteriosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.sunat.gob.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BimManager.Sunat.WS_Sunat_Consulta_Validez.statusResponse cdpvalidado;
        
        public validaCDPcriteriosResponse() {
        }
        
        public validaCDPcriteriosResponse(BimManager.Sunat.WS_Sunat_Consulta_Validez.statusResponse cdpvalidado) {
            this.cdpvalidado = cdpvalidado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface billValidServiceChannel : BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class billValidServiceClient : System.ServiceModel.ClientBase<BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService>, BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService {
        
        public billValidServiceClient() {
        }
        
        public billValidServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public billValidServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billValidServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public billValidServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoResponse BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService.verificaCPEarchivo(BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest request) {
            return base.Channel.verificaCPEarchivo(request);
        }
        
        public BimManager.Sunat.WS_Sunat_Consulta_Validez.statusResponse verificaCPEarchivo(string nombre, string archivo) {
            BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest inValue = new BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest();
            inValue.nombre = nombre;
            inValue.archivo = archivo;
            BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoResponse retVal = ((BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService)(this)).verificaCPEarchivo(inValue);
            return retVal.archivoverificado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoResponse> BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService.verificaCPEarchivoAsync(BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest request) {
            return base.Channel.verificaCPEarchivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoResponse> verificaCPEarchivoAsync(string nombre, string archivo) {
            BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest inValue = new BimManager.Sunat.WS_Sunat_Consulta_Validez.verificaCPEarchivoRequest();
            inValue.nombre = nombre;
            inValue.archivo = archivo;
            return ((BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService)(this)).verificaCPEarchivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosResponse BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService.validaCDPcriterios(BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest request) {
            return base.Channel.validaCDPcriterios(request);
        }
        
        public BimManager.Sunat.WS_Sunat_Consulta_Validez.statusResponse validaCDPcriterios(string rucEmisor, string tipoCDP, string serieCDP, string numeroCDP, string tipoDocIdReceptor, string numeroDocIdReceptor, string fechaEmision, double importeTotal, string nroAutorizacion) {
            BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest inValue = new BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest();
            inValue.rucEmisor = rucEmisor;
            inValue.tipoCDP = tipoCDP;
            inValue.serieCDP = serieCDP;
            inValue.numeroCDP = numeroCDP;
            inValue.tipoDocIdReceptor = tipoDocIdReceptor;
            inValue.numeroDocIdReceptor = numeroDocIdReceptor;
            inValue.fechaEmision = fechaEmision;
            inValue.importeTotal = importeTotal;
            inValue.nroAutorizacion = nroAutorizacion;
            BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosResponse retVal = ((BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService)(this)).validaCDPcriterios(inValue);
            return retVal.cdpvalidado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosResponse> BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService.validaCDPcriteriosAsync(BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest request) {
            return base.Channel.validaCDPcriteriosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosResponse> validaCDPcriteriosAsync(string rucEmisor, string tipoCDP, string serieCDP, string numeroCDP, string tipoDocIdReceptor, string numeroDocIdReceptor, string fechaEmision, double importeTotal, string nroAutorizacion) {
            BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest inValue = new BimManager.Sunat.WS_Sunat_Consulta_Validez.validaCDPcriteriosRequest();
            inValue.rucEmisor = rucEmisor;
            inValue.tipoCDP = tipoCDP;
            inValue.serieCDP = serieCDP;
            inValue.numeroCDP = numeroCDP;
            inValue.tipoDocIdReceptor = tipoDocIdReceptor;
            inValue.numeroDocIdReceptor = numeroDocIdReceptor;
            inValue.fechaEmision = fechaEmision;
            inValue.importeTotal = importeTotal;
            inValue.nroAutorizacion = nroAutorizacion;
            return ((BimManager.Sunat.WS_Sunat_Consulta_Validez.billValidService)(this)).validaCDPcriteriosAsync(inValue);
        }
    }
}
